# Site settings
title: Platypus.js blog
email: info@altsoft.biz
description: > # this means to ignore newlines until "baseurl:"
  Platypus.js blog. Новости, описания архитертурных решений и проблем постятся здесь.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.platypus-platform.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge